<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Project="$(KoreBuildTasksPath)\Microsoft.AspNetCore.Build.Tasks.tasks" />
    <Target Name="Build">
        <KoreBuildTest />
        <Error Text="KoreBuild 2.0 is not ready yet!" />
    </Target>
</Project>
