<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" InitialTargets="Initialize" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildThisFileDirectory)\ProductInfo.props" />
  <Import Project="$(MSBuildThisFileDirectory)\StandardLifecycle.targets" />
  <Import Project="$(MSBuildThisFileDirectory)\StandardBuild.targets" />
</Project>
